# Credits: Adapted from https://github.com/choderalab/pymbar/.travis.yml
# with some modifications
language: C
sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install_miniconda.sh
  - export PYTHONUNBUFFERED=true
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --add channels conda-forge # hightest priority
  - conda config --add channels omnia

script:
  # Add org channel
  - conda config --add channels ${ORGNAME}
  # Create a test environment
  - conda create --quiet --yes -n test python=$python
  # Activate root environment
  #- source activate root
  # Activate the test environment
  - source activate test
  # Get conda info
  - conda info 
  # Get environment info
  - conda list --explicit 
  # Build recipie
  - conda build devtools/conda-recipe
  #- conda-build devtools/conda-recipe -c conda-forge/label/gcc7
  # Install locally-built package
  - conda install --yes --quiet --use-local ${PACKAGENAME}
  #- conda install --yes --quiet pip nose nose-timer
  # Test the package (will do this once unit tests are ready)
  #- cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer && cd ..

os:
  - osx
  - linux

env:
  matrix:
    - python=2.7  CONDA_PY=27
#    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36
    
  global:
    - PACKAGENAME="sstmap"
    - ORGNAME="solvationtools"

after_success:
  - source devtools/travis-ci/deploy_anaconda.sh
